AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ExecutionRoleName:
    Type: String
    Default: AWSCloudFormationStackSetExecutionRole
    Description: "The name of the execution role. Defaults to 'AWSCloudFormationStackSetExecutionRole'."
  AdministratorRoleName:
    Type: String
    Default: AWSCloudFormationStackSetAdministrationRole
    Description: "The name of the Administrator role. Defaults to 'AWSCloudFormationStackSetAdministrationRole'."
  CFNDelegatedAdministrator:
    Type: String
    Default: "703671934534"
    Description: 12 digit account id of SecurityHub Administrator account

Resources: 
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ExecutionRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CFNDelegatedAdministrator
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
  AdministratorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AdministratorRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
          - PolicyName: "UpdateSecurityHub"
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Sid: CloudFormationPermissions
                  Effect: Allow
                  Action:
                    - sts:AssumeRole
                  Resource: !Sub "arn:aws:iam::*:role/${ExecutionRoleName}"
