AWSTemplateFormatVersion: 2010-09-09
Description: AWS Config rule for SSH and RDP

Parameters:
  AutomationRoleName:
    Type: String
    Default: "ConfigAutoRemediationRole"
    Description: role Name
  AccountInventoryTable:
    Type: String
    Description: The name of the DynamoDB table
  ResourceExclussionTable:
    Type: String
    Description: The name of the DynamoDB table
  SecToolingS3QuickSightBucket:
    Type: String
    Description: Name of Quick Sight S3 bucket for Security Tooling

Resources:
  # -------------------------------------------------------------------------------------------------------------------------------------------------------
  # [EC2.14] Security groups should not allow ingress from 0.0.0.0/0 or ::/0 to port 3389
  # -------------------------------------------------------------------------------------------------------------------------------------------------------
  SSMDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      Name: DisablePublicAccessForSecurityGroup
      Content:
        description: >-
          ## Disable RDP ports opened to IP address specified,
           or to all addresses if no address is specified. 
           Similar to the [RevokeSecurityGroupIngress](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RevokeSecurityGroupIngress.html) API, 
           the security group must have existing rules specifically on the SSH and RDP ports in order for ingress to be disabled.
        schemaVersion: '0.3'
        assumeRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${AutomationRoleName}'
        parameters:
          AccountId:
            type: String
            default: !Sub ${AWS::AccountId}
          ResourceType:
            type: String
            default: 'AWS::EC2::SecurityGroup'
          ControlId:
            type: String
            default: "EC2.14"
          AutomationAssumeRole:
            type: String
            default: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${AutomationRoleName}'
          GroupId:
            type: String
            description: (Required) Security Group ID
            allowedPattern: ^([s][g]\-)([0-9a-f]){1,}$
          IpAddressToBlock:
            type: String
            description: (Optional) Additional Ipv4 or Ipv6 address to block access from (ex:1.2.3.4/32)
            allowedPattern: (^$)|^((25[0-5]|(2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3})|(^((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?)::((?:[0-9A-Fa-f]{1,4}(?::[0-9A-Fa-f]{1,4})*)?))|(^(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}))\/(25[0-5]|2[0-4]\d|[0-1]?\d?\d)$
            default: ""
          GetTagsLambda:
            type: String
            default: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:GetTagsbyResource"
          GetInventoryLambda:
            type: String
            default: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:GetAccountInventory"
          ExclusionTable:
            type: String
            default: !Ref ResourceExclussionTable
          InventoryTable:
            type: String
            default: !Ref AccountInventoryTable
          QuickSightS3:
            type: String
            default: !Ref SecToolingS3QuickSightBucket
        mainSteps:
          - action: 'aws:invokeLambdaFunction'
            name: 'InvokeMyLambdaFunction'
            inputs:
              FunctionName: '{{GetTagsLambda}}'
              Payload: !Sub |
                {
                  "account_id": ${AWS::AccountId},
                  "resource_type": "{{ResourceType}}",
                  "resource_id": "{{GroupId}}",
                  "control_id": "{{ControlId}}",
                  "ddb_table": "{{ExclusionTable}}"
                }
          - name: LambdaOutputCheck
            action: aws:branch
            inputs:
              Choices:
              - NextStep: DisableRDPFromIpV4
                Variable: "{{InvokeMyLambdaFunction.Payload}}"
                StringEquals: "NotExcluded"
              - NextStep: DisableRDPFromIpV6
                Variable: "{{InvokeMyLambdaFunction.Payload}}"
                StringEquals: "NotExcluded"
              - NextStep: PublishExcludeLambda
                Variable: "{{InvokeMyLambdaFunction.Payload}}"
                StringEquals: "Excluded"
              Default:
                DisableRDPFromIpV4
          - name: PublishExcludeLambda
            action: 'aws:invokeLambdaFunction'
            inputs:
              FunctionName: '{{GetInventoryLambda}}'
              Payload: !Sub |
                {
                  "account_id": ${AWS::AccountId},
                  "S3Bucket": "{{QuickSightS3}}",
                  "region": "${AWS::Region}",
                  "status": "excluded",
                  "resource_id": "{{GroupId}}",
                  "control_id": "{{ControlId}}",
                  "ddb_table": "{{InventoryTable}}"
                }
            isEnd: true
          - name: DisableRDPFromIpV4
            action: "aws:executeAwsApi"
            inputs:
              Service: ec2
              Api: RevokeSecurityGroupIngress
              GroupId: "{{GroupId}}"
              IpPermissions:
                - IpProtocol: tcp
                  FromPort: 3389
                  ToPort: 3389
                  IpRanges:
                    - CidrIp: 0.0.0.0/0
            onFailure: Continue
          - name: DisableRDPFromIpV6
            action: "aws:executeAwsApi"
            inputs:
              Service: ec2
              Api: RevokeSecurityGroupIngress
              GroupId: "{{GroupId}}"
              IpPermissions:
                - IpProtocol: tcp
                  FromPort: 3389
                  ToPort: 3389
                  Ipv6Ranges:
                    - CidrIpv6: "::/0"
            onFailure: Continue
          - name: PublishRemediationLambda
            action: 'aws:invokeLambdaFunction'
            inputs:
              FunctionName: '{{GetInventoryLambda}}'
              Payload: !Sub |
                {
                  "account_id": ${AWS::AccountId},
                  "S3Bucket": "{{QuickSightS3}}",
                  "region": "${AWS::Region}",
                  "status": "remediated",
                  "resource_id": "{{GroupId}}",
                  "control_id": "{{ControlId}}",
                  "ddb_table": "{{InventoryTable}}"
                }
            isEnd: true
  AWSConfigRule:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: RestrictRDPPublicAccess-Tags
      Description: Restrict public access to 3389 port
      InputParameters:
        blockedPort1: 3389
      Scope: 
        ComplianceResourceTypes: 
          - AWS::EC2::SecurityGroup
      Source:
          Owner: AWS
          SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC
  ConfigAutoremediation:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      Automatic: true
      ConfigRuleName: !Ref AWSConfigRule
      MaximumAutomaticAttempts: 3
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values: 
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${AutomationRoleName}'
        GroupId:
          ResourceValue:
            Value: RESOURCE_ID
      RetryAttemptSeconds: 30
      TargetId: !Ref SSMDocument
      TargetType: "SSM_DOCUMENT"
