AWSTemplateFormatVersion: 2010-09-09
Description: AWS Config rule for SSH and RDP

Parameters:
  AutomationRoleName:
    Type: String
    Default: "FTA-ConfigAutoRemediation"
    Description: role Name

Resources:
  # -------------------------------------------------------------------------------------------------------------------------------------------------------
  # [EC2.14] Security groups should not allow ingress from 0.0.0.0/0 or ::/0 to port 3389
  # -------------------------------------------------------------------------------------------------------------------------------------------------------
  DisablePublicAccessToRDSInstance:
    Type: AWS::SSM::Document
    Properties:
      UpdateMethod: NewVersion
      DocumentType: Automation
      Name: FTA-DisablePublicAccessToRDSInstance-WithTags
      Content:
        description: >-
          ### Document name - AWSConfigRemediation-DisablePublicAccessToRDSInstance

          ## What does this document do?
          The runbook disables public accessibility for the Amazon RDS database instance you specify using
          the [ModifyDBInstance](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html) API.

          ## Input Parameters
          * AutomationAssumeRole: (Required) The Amazon Resource Name (ARN) of the AWS Identity and Access Management (IAM) role that allows Systems Manager Automation to perform the actions on your behalf.
          * DbiResourceId: (Required) The resource identifier for the DB instance you want to disable public accessibility.

          ## Output Parameters
          * DisablePubliclyAccessibleOnRDS.Response: The standard HTTP response from the ModifyDBInstance API.
        schemaVersion: '0.3'
        assumeRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${AutomationRoleName}'
        parameters:
          AutomationAssumeRole:
            type: String
            description: (Required) The Amazon Resource Name (ARN) of the AWS Identity and Access Management (IAM) role that allows Systems Manager Automation to perform the actions on your behalf.
            allowedPattern: ^arn:aws[a-z0-9-]*:iam::\d{12}:role\/[\w-\/.@+=,]{1,1017}$
          DbiResourceId:
            type: String
            description: (Required) The resource identifier for the DB instance you want to disable public accessibility.
            allowedPattern: "db-[A-Z0-9]{26}"
          AwsService:
            type: String
            default: 'rds'
          AccountId:
            type: String
            default: !Sub ${AWS::AccountId}
          ResourceType:
            type: String
            default: 'db'
          Partition:
            type: String
            default: "aws"
          ControlId:
            type: String
            default: "RDS.2"
          GetTagsLambda:
            type: String
            default: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:FTA-GetTagsbyResource-test"
          GetInventoryLambda:
            type: String
            default: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:FTA-GetAccountInventory"
          ExclusionTable:
            type: String
            default: "arn:aws:dynamodb:us-east-1:412090077236:table/FTA-resource-tags-exclusion-5d9747"
          InventoryTable:
            type: String
            default: "arn:aws:dynamodb:us-east-1:412090077236:table/FTA-Account-Inventory-f74cd8"
          QuickSightS3:
            type: String
            default: "quick-sight-report-exclusion-622c56"
        outputs:
          - DisablePubliclyAccessibleOnRDS.Response
        mainSteps:
          - name: 'InvokeMyLambdaFunction'
            action: 'aws:invokeLambdaFunction'
            inputs:
              FunctionName: '{{GetTagsLambda}}'
              Payload: !Sub |
                {
                  "account_id": ${AWS::AccountId},
                  "aws_service": "{{AwsService}}",
                  "region": "${AWS::Region}",
                  "resource_type": "{{ResourceType}}",
                  "resource_id": "{{DbiResourceId}}",
                  "partition": "{{Partition}}",
                  "control_id": "{{ControlId}}",
                  "ddb_table": "{{ExclusionTable}}"
                }
          - name: LambdaOutputCheck
            action: aws:branch
            inputs:
              Choices:
              - NextStep: GetRDSInstanceIdentifier
                Variable: "{{InvokeMyLambdaFunction.Payload}}"
                StringEquals: "NotExcluded"
              - NextStep: PublishExcludeLambda
                Variable: "{{InvokeMyLambdaFunction.Payload}}"
                StringEquals: "Excluded"
              Default:
                GetRDSInstanceIdentifier
          - name: PublishExcludeLambda
            action: 'aws:invokeLambdaFunction'
            inputs:
              FunctionName: '{{GetInventoryLambda}}'
              Payload: !Sub |
                {
                  "account_id": ${AWS::AccountId},
                  "S3Bucket": "{{QuickSightS3}}",
                  "region": "${AWS::Region}",
                  "status": "excluded",
                  "resource_id": "{{DbiResourceId}}",
                  "control_id": "{{ControlId}}",
                  "ddb_table": "{{InventoryTable}}"
                }
            isEnd: true
          -
            name: GetRDSInstanceIdentifier
            action: "aws:executeAwsApi"
            description: |
              ## GetRDSInstanceIdentifier
              Gathers the DB instance identifier from the DB instance resource identifier.
              ## Outputs
              * DbInstanceIdentifier: The Amazon RDS DB instance identifier.
            timeoutSeconds: 600
            isEnd: false
            inputs:
              Service: rds
              Api: DescribeDBInstances
              Filters:
                - Name: "dbi-resource-id"
                  Values:
                    - "{{ DbiResourceId }}"
            outputs:
              - Name: DbInstanceIdentifier
                Selector: $.DBInstances[0].DBInstanceIdentifier
                Type: String
          -
            name: VerifyDBInstanceStatus
            action: "aws:waitForAwsResourceProperty"
            timeoutSeconds: 900
            isEnd: false
            description: |
              ## VerifyDBInstanceStatus
              Waits for and verifies the DB instances is in an AVAILABLE state.
            inputs:
              Service: rds
              Api: DescribeDBInstances
              DBInstanceIdentifier: "{{ GetRDSInstanceIdentifier.DbInstanceIdentifier }}"
              PropertySelector: "$.DBInstances[0].DBInstanceStatus"
              DesiredValues:
                - "available"
          -
            name: DisablePubliclyAccessibleOnRDS
            action: "aws:executeAwsApi"
            description: |
              ## DisablePubliclyAccessibleOnRDS
              Disables public accessibility on your DB instance.
              ## Outputs
              * Response: The standard HTTP response from the ModifyDBInstance API.
            timeoutSeconds: 600
            isEnd: false
            inputs:
              Service: rds
              Api: ModifyDBInstance
              DBInstanceIdentifier: "{{ GetRDSInstanceIdentifier.DbInstanceIdentifier }}"
              PubliclyAccessible: false
            outputs:
              - Name: Response
                Selector: $
                Type: StringMap
          -
            name: WaitForDBInstanceStatusToModify
            action: "aws:waitForAwsResourceProperty"
            timeoutSeconds: 600
            isEnd: false
            description: |
              ## WaitForDBInstanceStatusToModify
              Waits for the DB instance to change to a MODIFYING state.
            inputs:
              Service: rds
              Api: DescribeDBInstances
              DBInstanceIdentifier: "{{ GetRDSInstanceIdentifier.DbInstanceIdentifier }}"
              PropertySelector: "$.DBInstances[0].DBInstanceStatus"
              DesiredValues:
                - "modifying"
          -
            name: WaitForDBInstanceStatusToAvailableAfterModify
            action: "aws:waitForAwsResourceProperty"
            timeoutSeconds: 600
            isEnd: false
            description: |
              ## WaitForDBInstanceStatusToAvailableAfterModify
              Waits for the DB instance to change to an AVAILABLE state
            inputs:
              Service: rds
              Api: DescribeDBInstances
              DBInstanceIdentifier: "{{ GetRDSInstanceIdentifier.DbInstanceIdentifier }}"
              PropertySelector: "$.DBInstances[0].DBInstanceStatus"
              DesiredValues:
                - "available"
          -
            name: VerifyDBInstancePubliclyAccess
            action: "aws:assertAwsResourceProperty"
            timeoutSeconds: 600
            isEnd: false
            description: |
              ## VerifyDBInstancePubliclyAccess
              Confirms public accessibility is disabled on the DB instance.
            inputs:
              Service: rds
              Api: DescribeDBInstances
              DBInstanceIdentifier: "{{ GetRDSInstanceIdentifier.DbInstanceIdentifier }}"
              PropertySelector: "$.DBInstances[0].PubliclyAccessible"
              DesiredValues:
                - "False"
          - name: PublishRemediationLambda
            action: 'aws:invokeLambdaFunction'
            inputs:
              FunctionName: '{{GetInventoryLambda}}'
              Payload: !Sub |
                {
                  "account_id": ${AWS::AccountId},
                  "S3Bucket": "{{QuickSightS3}}",
                  "region": "${AWS::Region}",
                  "status": "remediated",
                  "resource_id": "{{DbiResourceId}}",
                  "control_id": "{{ControlId}}",
                  "ddb_table": "{{InventoryTable}}"
                }
            isEnd: true
  AWSConfigRule:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: rds-instance-public-access-check
      Description: Checks if the Amazon Relational Database Service (Amazon RDS) instances are not publicly accessible. The rule is NON_COMPLIANT if the publiclyAccessible field is true in the instance configuration item.
      Scope: 
        ComplianceResourceTypes: 
          - AWS::RDS::DBInstance
      Source:
          Owner: AWS
          SourceIdentifier: RDS_INSTANCE_PUBLIC_ACCESS_CHECK
  ConfigAutoremediation:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      Automatic: true
      ConfigRuleName: !Ref AWSConfigRule
      MaximumAutomaticAttempts: 3
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values: 
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${AutomationRoleName}'
        DbiResourceId:
          ResourceValue:
            Value: RESOURCE_ID
      RetryAttemptSeconds: 30
      TargetId: !Ref DisablePublicAccessToRDSInstance
      TargetType: "SSM_DOCUMENT"
